CREATE TABLE IF NOT EXISTS  Person (
 id SERIAL PRIMARY KEY,  
 motherName VARCHAR(200) NOT NULL,  
 fatherName VARCHAR(200) NOT NULL,  
 name VARCHAR(200) NOT NULL,  
 rg VARCHAR(200) NOT NULL, 
 dateBirth DATE NOT NULL,  
 cpf VARCHAR(200) NOT NULL,  
 altura FLOAT NOT NULL  
);

CREATE TABLE IF NOT EXISTS Characteristic (
 id SERIAL PRIMARY KEY,  
 description VARCHAR(200) NOT NULL  
);

CREATE TABLE IF NOT EXISTS  CrimeType (
 id SERIAL PRIMARY KEY,
 name VARCHAR(200) NOT NULL  
);


CREATE TABLE IF NOT EXISTS Crime (
 id SERIAL PRIMARY KEY,  
 data DATE NOT NULL,  
 crimeTypeID INT NOT NULL REFERENCES CrimeType (id)
);

CREATE TABLE IF NOT EXISTS Vehicle (
 id SERIAL PRIMARY KEY,  
 type VARCHAR(200) NOT NULL,  
 plateNumber VARCHAR(200) NOT NULL,  
 model VARCHAR(200) NOT NULL  
);

CREATE TABLE IF NOT EXISTS Weapon (
 id SERIAL PRIMARY KEY,  
 type VARCHAR(200) NOT NULL,  
 register VARCHAR(200) NOT NULL,  
 description VARCHAR(200) NOT NULL  
);

CREATE TABLE IF NOT EXISTS CrimePhoto (
 id SERIAL PRIMARY KEY,  
 photo BYTEA NOT NULL,  
 description VARCHAR(200) NOT NULL  
);

CREATE TABLE IF NOT EXISTS Characteristic (
 id SERIAL NOT NULL,  
 description VARCHAR(200) NOT NULL
);


CREATE TABLE IF NOT EXISTS Person_Characteristic (
 personID INT NOT NULL REFERENCES Person(id),  
 characteristic INT NOT NULL REFERENCES Characteristic(id) 
);


CREATE TABLE IF NOT EXISTS Person_Crime (
 personID INT NOT NULL REFERENCES Person(id),  
 crimeID INT NOT NULL REFERENCES Crime(id) 
);

CREATE TABLE IF NOT EXISTS Crime_Vehicle (
 vehicleID SERIAL NOT NULL REFERENCES Vehicle(id),  
 crimeID SERIAL NOT NULL REFERENCES Crime(id)
);

CREATE TABLE IF NOT EXISTS Crime_Weapon (
 weaponID SERIAL NOT NULL REFERENCES Weapon(id),  
 crimeID SERIAL NOT NULL REFERENCES Crime(id)
);
